changeinclude: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: warning
    must_be_immutable : ignore
    constant_identifier_names : ignore
    depend_on_referenced_packages : ignore
    use_build_context_synchronously : ignore
  
linter:
  rules:
    - avoid_print
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - prefer_const_constructors
    - camel_case_types
    - avoid_empty_else
    - unnecessary_brace_in_string_interps
    - curly_braces_in_flow_control_structures
    - sort_child_properties_last
    - unnecessary_const
    - prefer_null_aware_operators
    - unnecessary_this
    - avoid_single_cascade_in_expression_statements
    - comment_references
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - collection_methods_unrelated_type
    - always_declare_return_types
    - avoid_multiple_declarations_per_line
    - unnecessary_new
    - depend_on_referenced_packages
    - prefer_final_fields